// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApiVOdNl_jI49n6k03K8wFkn3ay5_9_xE',
    appId: '1:440428506573:web:b852dd4fe8b17315f96884',
    messagingSenderId: '440428506573',
    projectId: 'mobileproject-7f990',
    authDomain: 'mobileproject-7f990.firebaseapp.com',
    storageBucket: 'mobileproject-7f990.appspot.com',
    measurementId: 'G-SY2GZM5976',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNcLBz_0pYhYHKpJygCcBRWNo2O0HvjZI',
    appId: '1:440428506573:android:487b64c2459376f5f96884',
    messagingSenderId: '440428506573',
    projectId: 'mobileproject-7f990',
    storageBucket: 'mobileproject-7f990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAubVPNhQWpv07gnbNfjRXq6yNRhobMM',
    appId: '1:440428506573:ios:325022d9ce8a7f88f96884',
    messagingSenderId: '440428506573',
    projectId: 'mobileproject-7f990',
    storageBucket: 'mobileproject-7f990.appspot.com',
    iosClientId: '440428506573-ruflvcj3ib4c2qai8i6an2m6lvnp8us2.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.langev.mobile5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAubVPNhQWpv07gnbNfjRXq6yNRhobMM',
    appId: '1:440428506573:ios:325022d9ce8a7f88f96884',
    messagingSenderId: '440428506573',
    projectId: 'mobileproject-7f990',
    storageBucket: 'mobileproject-7f990.appspot.com',
    iosClientId: '440428506573-ruflvcj3ib4c2qai8i6an2m6lvnp8us2.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.langev.mobile5',
  );
}
